/* 
 * Activiti REST API
 *
 * # activiti     - Activiti is battle-tested Business Process Management. Organizations across the world depend on the open source platform in a huge range of demanding situations. It supports open standards with BPMN and DMN so you can create processes that suit you.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Activiti.Rest.Client;
using Activiti.Rest.Api;
using Activiti.Rest.Model;

namespace Activiti.Rest.Test
{
    /// <summary>
    ///  Class for testing FormsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class FormsApiTests
    {
        private FormsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new FormsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FormsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' FormsApi
            //Assert.IsInstanceOfType(typeof(FormsApi), instance, "instance is a FormsApi");
        }

        
        /// <summary>
        /// Test GetFormData
        /// </summary>
        [Test]
        public void GetFormDataTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string taskId = null;
            //string processDefinitionId = null;
            //var response = instance.GetFormData(taskId, processDefinitionId);
            //Assert.IsInstanceOf<FormDataResponse> (response, "response is FormDataResponse");
        }
        
        /// <summary>
        /// Test SubmitForm
        /// </summary>
        [Test]
        public void SubmitFormTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SubmitFormRequest body = null;
            //var response = instance.SubmitForm(body);
            //Assert.IsInstanceOf<ProcessInstanceResponse> (response, "response is ProcessInstanceResponse");
        }
        
    }

}
