/* 
 * Activiti REST API
 *
 * # activiti     - Activiti is battle-tested Business Process Management. Organizations across the world depend on the open source platform in a huge range of demanding situations. It supports open standards with BPMN and DMN so you can create processes that suit you.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Activiti.Rest.Api;
using Activiti.Rest.Model;
using Activiti.Rest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Activiti.Rest.Test
{
    /// <summary>
    ///  Class for testing EventResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EventResponseTests
    {
        // TODO uncomment below to declare an instance variable for EventResponse
        //private EventResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EventResponse
            //instance = new EventResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EventResponse
        /// </summary>
        [Test]
        public void EventResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EventResponse
            //Assert.IsInstanceOfType<EventResponse> (instance, "variable 'instance' is a EventResponse");
        }


        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Test]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'TaskUrl'
        /// </summary>
        [Test]
        public void TaskUrlTest()
        {
            // TODO unit test for the property 'TaskUrl'
        }
        /// <summary>
        /// Test the property 'ProcessInstanceUrl'
        /// </summary>
        [Test]
        public void ProcessInstanceUrlTest()
        {
            // TODO unit test for the property 'ProcessInstanceUrl'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
