/* 
 * Activiti REST API
 *
 * # activiti     - Activiti is battle-tested Business Process Management. Organizations across the world depend on the open source platform in a huge range of demanding situations. It supports open standards with BPMN and DMN so you can create processes that suit you.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Activiti.Rest.Api;
using Activiti.Rest.Model;
using Activiti.Rest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Activiti.Rest.Test
{
    /// <summary>
    ///  Class for testing HistoricTaskInstanceResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HistoricTaskInstanceResponseTests
    {
        // TODO uncomment below to declare an instance variable for HistoricTaskInstanceResponse
        //private HistoricTaskInstanceResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HistoricTaskInstanceResponse
            //instance = new HistoricTaskInstanceResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HistoricTaskInstanceResponse
        /// </summary>
        [Test]
        public void HistoricTaskInstanceResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HistoricTaskInstanceResponse
            //Assert.IsInstanceOfType<HistoricTaskInstanceResponse> (instance, "variable 'instance' is a HistoricTaskInstanceResponse");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionId'
        /// </summary>
        [Test]
        public void ProcessDefinitionIdTest()
        {
            // TODO unit test for the property 'ProcessDefinitionId'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionUrl'
        /// </summary>
        [Test]
        public void ProcessDefinitionUrlTest()
        {
            // TODO unit test for the property 'ProcessDefinitionUrl'
        }
        /// <summary>
        /// Test the property 'ProcessInstanceId'
        /// </summary>
        [Test]
        public void ProcessInstanceIdTest()
        {
            // TODO unit test for the property 'ProcessInstanceId'
        }
        /// <summary>
        /// Test the property 'ProcessInstanceUrl'
        /// </summary>
        [Test]
        public void ProcessInstanceUrlTest()
        {
            // TODO unit test for the property 'ProcessInstanceUrl'
        }
        /// <summary>
        /// Test the property 'ExecutionId'
        /// </summary>
        [Test]
        public void ExecutionIdTest()
        {
            // TODO unit test for the property 'ExecutionId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'DeleteReason'
        /// </summary>
        [Test]
        public void DeleteReasonTest()
        {
            // TODO unit test for the property 'DeleteReason'
        }
        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Test]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'Assignee'
        /// </summary>
        [Test]
        public void AssigneeTest()
        {
            // TODO unit test for the property 'Assignee'
        }
        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Test]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }
        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Test]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }
        /// <summary>
        /// Test the property 'DurationInMillis'
        /// </summary>
        [Test]
        public void DurationInMillisTest()
        {
            // TODO unit test for the property 'DurationInMillis'
        }
        /// <summary>
        /// Test the property 'WorkTimeInMillis'
        /// </summary>
        [Test]
        public void WorkTimeInMillisTest()
        {
            // TODO unit test for the property 'WorkTimeInMillis'
        }
        /// <summary>
        /// Test the property 'ClaimTime'
        /// </summary>
        [Test]
        public void ClaimTimeTest()
        {
            // TODO unit test for the property 'ClaimTime'
        }
        /// <summary>
        /// Test the property 'TaskDefinitionKey'
        /// </summary>
        [Test]
        public void TaskDefinitionKeyTest()
        {
            // TODO unit test for the property 'TaskDefinitionKey'
        }
        /// <summary>
        /// Test the property 'FormKey'
        /// </summary>
        [Test]
        public void FormKeyTest()
        {
            // TODO unit test for the property 'FormKey'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Test]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Test]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }
        /// <summary>
        /// Test the property 'ParentTaskId'
        /// </summary>
        [Test]
        public void ParentTaskIdTest()
        {
            // TODO unit test for the property 'ParentTaskId'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Test]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }
        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Test]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }

    }

}
