/* 
 * Activiti REST API
 *
 * # activiti     - Activiti is battle-tested Business Process Management. Organizations across the world depend on the open source platform in a huge range of demanding situations. It supports open standards with BPMN and DMN so you can create processes that suit you.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Activiti.Rest.Api;
using Activiti.Rest.Model;
using Activiti.Rest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Activiti.Rest.Test
{
    /// <summary>
    ///  Class for testing Lane
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LaneTests
    {
        // TODO uncomment below to declare an instance variable for Lane
        //private Lane instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Lane
            //instance = new Lane();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Lane
        /// </summary>
        [Test]
        public void LaneInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Lane
            //Assert.IsInstanceOfType<Lane> (instance, "variable 'instance' is a Lane");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'XmlRowNumber'
        /// </summary>
        [Test]
        public void XmlRowNumberTest()
        {
            // TODO unit test for the property 'XmlRowNumber'
        }
        /// <summary>
        /// Test the property 'XmlColumnNumber'
        /// </summary>
        [Test]
        public void XmlColumnNumberTest()
        {
            // TODO unit test for the property 'XmlColumnNumber'
        }
        /// <summary>
        /// Test the property 'ExtensionElements'
        /// </summary>
        [Test]
        public void ExtensionElementsTest()
        {
            // TODO unit test for the property 'ExtensionElements'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Test]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ParentProcess'
        /// </summary>
        [Test]
        public void ParentProcessTest()
        {
            // TODO unit test for the property 'ParentProcess'
        }
        /// <summary>
        /// Test the property 'FlowReferences'
        /// </summary>
        [Test]
        public void FlowReferencesTest()
        {
            // TODO unit test for the property 'FlowReferences'
        }

    }

}
