/* 
 * Activiti REST API
 *
 * # activiti     - Activiti is battle-tested Business Process Management. Organizations across the world depend on the open source platform in a huge range of demanding situations. It supports open standards with BPMN and DMN so you can create processes that suit you.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Activiti.Rest.Api;
using Activiti.Rest.Model;
using Activiti.Rest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Activiti.Rest.Test
{
    /// <summary>
    ///  Class for testing RestFormProperty
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RestFormPropertyTests
    {
        // TODO uncomment below to declare an instance variable for RestFormProperty
        //private RestFormProperty instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RestFormProperty
            //instance = new RestFormProperty();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RestFormProperty
        /// </summary>
        [Test]
        public void RestFormPropertyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RestFormProperty
            //Assert.IsInstanceOfType<RestFormProperty> (instance, "variable 'instance' is a RestFormProperty");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Readable'
        /// </summary>
        [Test]
        public void ReadableTest()
        {
            // TODO unit test for the property 'Readable'
        }
        /// <summary>
        /// Test the property 'Writable'
        /// </summary>
        [Test]
        public void WritableTest()
        {
            // TODO unit test for the property 'Writable'
        }
        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [Test]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }
        /// <summary>
        /// Test the property 'DatePattern'
        /// </summary>
        [Test]
        public void DatePatternTest()
        {
            // TODO unit test for the property 'DatePattern'
        }
        /// <summary>
        /// Test the property 'EnumValues'
        /// </summary>
        [Test]
        public void EnumValuesTest()
        {
            // TODO unit test for the property 'EnumValues'
        }

    }

}
